# Base image with Python
FROM python:3.9-slim

# Install system dependencies for dlib & face_recognition
RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    libsm6 \
    libxext6 \
    libxrender-dev \
    libglib2.0-0 \
    libgl1-mesa-glx \
    libboost-all-dev \
    libatlas-base-dev \
    libdlib-dev \
    python3-dev \
    tesseract-ocr \
 && apt-get clean

# Set working directory
WORKDIR /app

# Copy files
COPY . /app

# Install Python dependencies
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Run the app
CMD ["streamlit", "run", "google_solution.py", "--server.port=8080", "--server.address=0.0.0.0"]
